# Generated by Django 4.2.1 on 2023-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('category', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('productqtt', models.IntegerField()),
            ],
        ),
    ]
