# Generated by Django 4.2.1 on 2023-05-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
